const MULT={
'54cb50c76803fa8b248b4571':0.50,'54cb57776803fa99248b456e':0.63,'579dc571d53a0658a154fbec':0.40,'58330581ace78e27b8b10cee':0.49,'5935c25fb3acc3127c3d8cd9':0.45,'5a7c2eca46aef81a7ca2145d':0.56,'5ac3b934156ae10c4430e83c':0.62,'5c0647fdd443bc2504c2d371':0.60,'6617beeaa9cfa777ca915b7c':0.60};
const TNAME={'54cb50c76803fa8b248b4571':'Прапор','54cb57776803fa99248b456e':'Терапевт','579dc571d53a0658a154fbec':'Скупщик','58330581ace78e27b8b10cee':'Лыжник','5935c25fb3acc3127c3d8cd9':'Миротворец','5a7c2eca46aef81a7ca2145d':'Механик','5ac3b934156ae10c4430e83c':'Барахольщик','5c0647fdd443bc2504c2d371':'Егерь','6617beeaa9cfa777ca915b7c':'Реф'};
let byId={},bartersByReward={},sacrifice=[null,null,null,null,null];
const costCache=new Map();
function esc(s){return String(s||'').replace(/&/g,'&').replace(/</g,'<').replace(/>/g,'>').replace(/"/g,'"');}
function fmt(n){if(n==null||!isFinite(n))return '—';return Math.round(n).toLocaleString('ru-RU');}
function humanize(slug){return (slug||'').replace(/-/g,' ');}
function pickId(obj){if(!obj)return null;if(typeof obj==='string')return obj;return obj.item||obj.itemId||obj.id||(obj.item&&obj.item.id)||null;}
function cultistValue(it){if(!it)return 0;const bp=Number(it.basePrice)||0;if(bp>0)return bp;let best=0;(it.sellToTrader||[]).forEach(s=>{const price=Number(s.priceRUB!=null?s.priceRUB:s.price)||0;const tid=s.trader||s.trader_id;const m=MULT[tid]||0.5;if(price>0&&m>0)best=Math.max(best,price/m);});return best;}
function traderBuyCost(it,allowQuest){let best=Infinity,meta=null;(it.buyFromTrader||[]).forEach(o=>{if(!allowQuest&&o.taskUnlock)return;const p=Number(o.priceRUB!=null?o.priceRUB:o.price)||0;if(p<=0)return;if(p<best){best=p;meta={price:p,path:(TNAME[o.trader]||'Торговец')+(o.minTraderLevel?(' LL'+o.minTraderLevel):'')+(o.taskUnlock?' [квест]':'')};}});return meta;}
function fleaCost(it){const p=Number(it.avg24hPrice)||Number(it.lastLowPrice)||0;if(!p)return null;return{price:p,path:'flea'};}
function acquireCost(itemId,depth,stack){const mode=document.getElementById('costMode').value;const allowQuest=document.getElementById('allowQuestBarter').checked;const maxD=Number(document.getElementById('barterDepth').value)||0;const key=itemId+'|'+mode+'|'+maxD+'|'+allowQuest+'|'+depth;if(costCache.has(key))return costCache.get(key);if(stack.has(itemId))return{price:Infinity,path:'цикл'};const it=byId[itemId];if(!it)return{price:Infinity,path:'?'};const candidates=[];if(mode==='trader'||mode==='both'){const t=traderBuyCost(it,allowQuest);if(t)candidates.push(t);}if(mode==='flea'||mode==='both'){const f=fleaCost(it);if(f)candidates.push(f);}if(depth<maxD){for(const b of(bartersByReward[itemId]||[])){if(!allowQuest&&b.quest)continue;let sum=0,parts=[],ok=true;const st2=new Set(stack);st2.add(itemId);for(const req of b.required){const c=acquireCost(req.id,depth+1,st2);if(!c||!isFinite(c.price)){ok=false;break;}sum+=c.price*(req.count||1);parts.push((req.count>1?(req.count+'×'):'')+(byId[req.id]?.shortName||req.id.slice(0,6)));}if(ok&&parts.length)candidates.push({price:sum,path:'бартер '+(b.traderName||'')+': '+parts.join('+')});}}if(!candidates.length){const r={price:Infinity,path:'нет цены'};costCache.set(key,r);return r;}candidates.sort((a,b)=>a.price-b.price);costCache.set(key,candidates[0]);return candidates[0];}
function refreshCosts(){costCache.clear();Object.values(byId).forEach(it=>{const ac=acquireCost(it.id,0,new Set());it._cost=ac.price;it._path=ac.path;it._value=cultistValue(it);it._eff=(isFinite(it._cost)&&it._cost>0)?(it._value/it._cost):0;});}
function ritualInfo(total){let tier='низкий',time='2–12 ч',note='';if(total>=400000){tier='400k+';time='6ч 25% / 14ч';note='квест/убежище';}else if(total>=350001){tier='350k+';time='14 ч';note='high-tier пул';}else if(total>=200001)time='12 ч';else if(total>=100001)time='8 ч';else if(total>=50001)time='5 ч';else if(total>=25001)time='4 ч';else if(total>=10001)time='3 ч';else time='2 ч';return{tier,time,note};}
function renderSlots(){const box=document.getElementById('slots');box.innerHTML=sacrifice.map((id,i)=>{if(!id||!byId[id])return '<div class="slot"><div class="meta">Слот '+(i+1)+'</div><div class="meta">пусто</div></div>';const it=byId[id];return '<div class="slot filled"><button type="button" class="btn-ghost rm" data-i="'+i+'">×</button>'+(it.icon?'<img class="ico" src="'+esc(it.icon)+'">':'')+'<div style="font-weight:600;margin-top:4px">'+esc(it.shortName)+'</div><div class="meta">base '+fmt(it._value)+'</div><div class="meta">cost '+fmt(it._cost)+'</div></div>';}).join('');box.querySelectorAll('.rm').forEach(b=>{b.onclick=()=>{sacrifice[+b.dataset.i]=null;renderSlots();};});renderSum();}
function renderSum(){let value=0,cost=0,n=0;sacrifice.forEach(id=>{if(!id||!byId[id])return;n++;value+=byId[id]._value||0;if(isFinite(byId[id]._cost))cost+=byId[id]._cost;});const amulet=document.getElementById('amulet').checked;const shown=amulet?value*1.15:value;const info=ritualInfo(shown);const ok350=shown>=350001;document.getElementById('sumStats').innerHTML='<div class="stat"><div class="v">'+fmt(shown)+'</div><div class="l">Base value'+(amulet?' (+15%)':'')+'</div></div><div class="stat"><div class="v">'+fmt(cost)+'</div><div class="l">Цена получения</div></div><div class="stat"><div class="v '+(ok350?'good':'bad')+'">'+esc(info.tier)+'</div><div class="l">'+esc(info.note||'тир')+'</div></div><div class="stat"><div class="v">'+esc(info.time)+'</div><div class="l">таймер</div></div><div class="stat"><div class="v">'+n+'/5</div><div class="l">слотов</div></div><div class="stat"><div class="v">'+(ok350?fmt(shown-350001):fmt(350001-shown))+'</div><div class="l">'+(ok350?'сверх 350k':'до 350k')+'</div></div>';}
function renderTable(){const q=(document.getElementById('q').value||'').toLowerCase();const sort=document.getElementById('sortBy').value;let list=Object.values(byId).filter(it=>{if(!it._value)return false;if(!q)return true;return(it.shortName+' '+it.slug+' '+(it.name||'')).toLowerCase().includes(q);});list.sort((a,b)=>{if(sort==='name')return a.shortName.localeCompare(b.shortName,'ru');if(sort==='value')return(b._value||0)-(a._value||0);if(sort==='cost')return(a._cost||Infinity)-(b._cost||Infinity);return(b._eff||0)-(a._eff||0);});list=list.slice(0,400);document.getElementById('tbody').innerHTML=list.map(it=>'<tr data-id="'+esc(it.id)+'" style="cursor:pointer"><td><div class="name-cell">'+(it.icon?'<img class="ico-sm" src="'+esc(it.icon)+'" loading="lazy">':'')+'<div><div>'+esc(it.shortName)+'</div><div class="meta">'+esc(it.slug)+'</div></div></div></td><td><strong>'+fmt(it._value)+'</strong></td><td>'+fmt(it._cost)+'</td><td>'+(it._eff?it._eff.toFixed(2):'—')+'</td><td class="path">'+esc(it._path||'')+'</td></tr>').join('');document.querySelectorAll('#tbody tr').forEach(tr=>{tr.onclick=()=>addToSacrifice(tr.dataset.id);});}
function addToSacrifice(id){const idx=sacrifice.findIndex(x=>!x);if(idx<0){alert('Все 5 слотов заняты');return;}sacrifice[idx]=id;renderSlots();if(window.TarkovTools&&TarkovTools.beep)TarkovTools.beep('ok');}
function fillTo(target){let value=0;sacrifice.forEach(id=>{if(id&&byId[id])value+=byId[id]._value||0;});const need=document.getElementById('amulet').checked?target/1.15-value:target-value;if(need<=0)return;const free=sacrifice.map((x,i)=>!x?i:-1).filter(i=>i>=0);const used=new Set(sacrifice.filter(Boolean));let cands=Object.values(byId).filter(it=>it._value>0&&isFinite(it._cost)&&it._cost>0&&!used.has(it.id));cands.sort((a,b)=>(b._eff||0)-(a._eff||0));let remain=need;for(const slot of free){if(remain<=0)break;let pick=cands.find(it=>!used.has(it.id)&&it._value>=remain*0.15);if(!pick)pick=cands.find(it=>!used.has(it.id));if(!pick)break;sacrifice[slot]=pick.id;used.add(pick.id);remain-=pick._value;}renderSlots();}
document.getElementById('loadBtn').onclick=async()=>{const st=document.getElementById('status');const btn=document.getElementById('loadBtn');btn.disabled=true;st.className='status';st.textContent='Гружу items + barters…';try{const mode=document.getElementById('gameMode').value||'pve';const[ri,rb]=await Promise.all([fetch('https://json.tarkov.dev/'+mode+'/items',{cache:'no-store'}),fetch('https://json.tarkov.dev/'+mode+'/barters',{cache:'no-store'})]);if(!ri.ok)throw new Error('items HTTP '+ri.status);if(!rb.ok)throw new Error('barters HTTP '+rb.status);const ji=await ri.json(),jb=await rb.json();let raw=ji?.data?.items;const items=Array.isArray(raw)?raw:Object.values(raw||{});byId={};items.forEach(it=>{byId[it.id]={id:it.id,slug:it.normalizedName||'',shortName:it.shortName||humanize(it.normalizedName),name:it.name||'',icon:it.iconLink||it.gridImageLink||'',basePrice:Number(it.basePrice)||0,avg24hPrice:it.avg24hPrice,lastLowPrice:it.lastLowPrice,buyFromTrader:it.buyFromTrader||[],sellToTrader:it.sellToTrader||[]};});let bars=jb?.data?.barters;if(!bars)bars=jb?.data;if(typeof bars==='object'&&!Array.isArray(bars)){for(const k of Object.keys(bars)){if(Array.isArray(bars[k])){bars=bars[k];break;}}}if(!Array.isArray(bars))bars=[];bartersByReward={};bars.forEach(b=>{const rewardItems=b.rewardItems||b.rewards||[];const reqItems=b.requiredItems||b.requirements||b.required||[];const trader=typeof b.trader==='object'?(b.trader.id||b.trader):(b.trader||b.trader_id);const traderName=(typeof b.trader==='object'&&b.trader?.name)||TNAME[trader]||'';const quest=!!(b.taskUnlock||b.quest||b.unlock);const required=(Array.isArray(reqItems)?reqItems:[]).map(r=>{const id=pickId(r);return id?{id,count:Number(r.count||r.quantity||1)||1}:null;}).filter(Boolean);(Array.isArray(rewardItems)?rewardItems:[]).forEach(rw=>{const id=pickId(rw);if(!id||(Number(rw.count||1)||1)!==1)return;if(!bartersByReward[id])bartersByReward[id]=[];bartersByReward[id].push({required,trader,traderName,quest});});});refreshCosts();renderTable();renderSlots();st.className='status ok';st.textContent='Предметов: '+Object.keys(byId).length+' · бартеров: '+bars.length+' · с ценой: '+Object.values(byId).filter(x=>isFinite(x._cost)).length;}catch(e){st.className='status err';st.textContent=e.message;}finally{btn.disabled=false;}};
document.getElementById('q').oninput=renderTable;
document.getElementById('sortBy').onchange=renderTable;
['costMode','barterDepth','allowQuestBarter'].forEach(id=>{document.getElementById(id).onchange=()=>{if(Object.keys(byId).length){refreshCosts();renderTable();renderSlots();};});});
document.getElementById('amulet').onchange=renderSum;
document.getElementById('clearBtn').onclick=()=>{sacrifice=[null,null,null,null,null];renderSlots();};
document.getElementById('fill350').onclick=()=>fillTo(350001);
document.getElementById('fill400').onclick=()=>fillTo(400000);
renderSlots();
