#!/usr/bin/env python3
"""
Собирает hub/catalog-data.js из tools/*.html → #tarkovtool-meta.

Каждый тул сам описывает себя. Каталог не правится руками.

  python3 scripts/build-catalog.py

Мета (JSON в <script type="application/json" id="tarkovtool-meta">):
  {
    "title": "Название",
    "description": "Кратко",
    "kind": "static" | "live",
    "cat": "flea" | "loadout" | "hideout" | "quests" | "med" | "util" | "other",
    "icon": "optional-id"
  }

Если cat/kind/icon нет — выводятся из имени файла / title.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOOLS = ROOT / "tools"
OUT_HUB = ROOT / "hub" / "catalog-data.js"
OUT_ROOT = ROOT / "catalog-data.js"

CATEGORIES = {
    "flea": "Барахолка",
    "loadout": "Лоадаут",
    "hideout": "Убежка",
    "quests": "Квесты",
    "med": "Мед / еда",
    "util": "Утилиты",
    "other": "Прочее",
}

# keyword → cat (filename / title, lower)
CAT_HINTS = [
    (("barter", "price", "flea", "flip", "shopping", "alarm", "track", "restock"), "flea"),
    (("gun", "ammo", "armor", "helmet", "mag", "scope", "mod", "loadout", "drip", "nvg", "plate", "headphone"), "loadout"),
    (("hideout", "craft", "case", "container", "btc"), "hideout"),
    (("quest", "raid-checklist"), "quests"),
    (("med", "stim", "food"), "med"),
    (("season", "battle-pass", "hitbox", "xp", "repair", "prestige", "marathon", "challenge", "boss"), "util"),
]

LIVE_HINTS = ("live", "alarm", "track", "restock", "poll")

META_RE = re.compile(
    r'<script[^>]*\bid=["\']tarkovtool-meta["\'][^>]*>(.*?)</script>',
    re.S | re.I,
)


def slug_from_file(name: str) -> str:
    base = Path(name).name
    if base.startswith("tarkovtool-"):
        base = base[len("tarkovtool-") :]
    return Path(base).stem


def infer_cat(slug: str, title: str) -> str:
    blob = f"{slug} {title}".lower()
    for keys, cat in CAT_HINTS:
        if any(k in blob for k in keys):
            return cat
    return "other"


def infer_kind(slug: str, meta_kind: str | None) -> str:
    if meta_kind in ("static", "live"):
        return meta_kind
    blob = slug.lower()
    if any(k in blob for k in LIVE_HINTS):
        return "live"
    return "static"


def parse_meta(html: str) -> dict | None:
    m = META_RE.search(html)
    if not m:
        return None
    body = m.group(1).strip()
    # strip JS comments if someone left them
    if body.startswith("/*"):
        return None
    try:
        data = json.loads(body)
    except json.JSONDecodeError:
        return None
    if not isinstance(data, dict):
        return None
    return data


def collect() -> list[dict]:
    if not TOOLS.is_dir():
        print(f"ERROR: {TOOLS} not found", file=sys.stderr)
        sys.exit(1)

    tools: list[dict] = []
    warnings: list[str] = []

    for path in sorted(TOOLS.glob("tarkovtool-*.html")):
        slug = slug_from_file(path.name)
        raw = path.read_text(encoding="utf-8", errors="replace")
        meta = parse_meta(raw) or {}

        title = (meta.get("title") or slug).strip()
        description = (meta.get("description") or "").strip()
        cat = (meta.get("cat") or "").strip() or infer_cat(slug, title)
        if cat not in CATEGORIES:
            warnings.append(f"{path.name}: unknown cat={cat!r} → other")
            cat = "other"
        kind = infer_kind(slug, meta.get("kind"))
        icon = (meta.get("icon") or slug).strip()

        if not meta:
            warnings.append(f"{path.name}: no valid #tarkovtool-meta — used filename defaults")

        tools.append(
            {
                "file": f"tools/{path.name}",
                "title": title,
                "description": description,
                "icon": icon,
                "cat": cat,
                "kind": kind,
            }
        )

    return tools, warnings


def emit_js(tools: list[dict]) -> str:
    payload = {
        "version": 3,
        "generated": "scripts/build-catalog.py",
        "categories": CATEGORIES,
        "tools": tools,
    }
    body = json.dumps(payload, ensure_ascii=False, indent=2)
    return f"""/* Auto-generated by scripts/build-catalog.py — do not edit by hand */
window.__TT_CATALOG_DATA = {body};
(function () {{
  var d = window.__TT_CATALOG_DATA;
  if (!d || !d.tools) return;
  window.TarkovHubCATALOG = d.tools;
  window.TarkovHubCatalog = d.tools;
  window.CATALOG = d.tools;
  try {{
    window.dispatchEvent(new Event("tarkov-catalog-ready"));
  }} catch (e) {{}}
}})();
"""


def main() -> None:
    tools, warnings = collect()
    js = emit_js(tools)
    OUT_HUB.parent.mkdir(parents=True, exist_ok=True)
    OUT_HUB.write_text(js, encoding="utf-8")
    OUT_ROOT.write_text(js, encoding="utf-8")
    print(f"Wrote {OUT_HUB.relative_to(ROOT)} ({len(tools)} tools)")
    print(f"Wrote {OUT_ROOT.relative_to(ROOT)}")
    for w in warnings:
        print("  warn:", w)


if __name__ == "__main__":
    main()
