/* Auto-generated by scripts/build-catalog.py — do not edit by hand */
window.__TT_CATALOG_DATA = {
  "version": 3,
  "generated": "scripts/build-catalog.py",
  "categories": {
    "flea": "Барахолка",
    "loadout": "Лоадаут",
    "hideout": "Убежка",
    "quests": "Квесты",
    "med": "Мед / еда",
    "util": "Утилиты",
    "other": "Прочее"
  },
  "tools": [
    {
      "file": "tools/tarkovtool-ammo.html",
      "title": "Патроны",
      "description": "Пробитие по калибрам; скрытые статы патрона по наведению.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-armor.html",
      "title": "Броня",
      "description": "Рейтинг брони по классу, зонам, плитам, без упора в цену.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-barter-calc.html",
      "title": "Бартер (ручной)",
      "description": "Калькулятор выгодности бартера: компоненты, комиссия flea.",
      "icon": "flea",
      "cat": "flea",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-barter-live.html",
      "title": "Бартер (live)",
      "description": "Бартер с ценами барахолки через API, пресеты трейдов.",
      "icon": "flea",
      "cat": "flea",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-barter-opt.html",
      "title": "Оптимизатор бартера",
      "description": "Бартер под покупку в бюджет: реальные цены ингредиентов, не флип.",
      "icon": "flea",
      "cat": "flea",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-battle-pass.html",
      "title": "Боевой пропуск",
      "description": "Трекинг Kord Breach BP: доки, страницы, награды.",
      "icon": "util",
      "cat": "util",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-bosses.html",
      "title": "Боссы и гуны",
      "description": "Шансы боссов, таймеры карт, текущая локация гунов.",
      "icon": "quests",
      "cat": "quests",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-btc-farm.html",
      "title": "Биткоин-ферма",
      "description": "ROI майнинга: GPU, топливо, солнечная, Hideout Management, графики.",
      "icon": "hideout",
      "cat": "hideout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-cases.html",
      "title": "Ящики",
      "description": "Кейсы и контейнеры: что влезает. Сетка + поиск.",
      "icon": "hideout",
      "cat": "hideout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-challenge.html",
      "title": "Челлендж",
      "description": "Рандом: карта, задание, лоадаут. Особые правила, локальный XP.",
      "icon": "util",
      "cat": "util",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-compare.html",
      "title": "Сравнение",
      "description": "Сравнение нескольких предметов одной категории, моды под ствол.",
      "icon": "other",
      "cat": "other",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-containers.html",
      "title": "Разгрузки и рюкзаки",
      "description": "Рейтинг контейнеров: слоты, вес, сегменты.",
      "icon": "hideout",
      "cat": "hideout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-crafts.html",
      "title": "Крафты убежища",
      "description": "ROI крафтов hideout, цены, время.",
      "icon": "hideout",
      "cat": "hideout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-cultist.html",
      "title": "Круг культистов",
      "description": "Base value 350k/400k, цена: торговцы / flea / бартер-цепочки.",
      "icon": "other",
      "cat": "other",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-desk.html",
      "title": "Desk",
      "description": "Мини-вкладки: несколько инструментов сразу поверх общего состояния.",
      "icon": "other",
      "cat": "other",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-drip-builder.html",
      "title": "Дрип-билдер (моды)",
      "description": "Поиск модов оружия по цветам — заглушка.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-drip-loadout.html",
      "title": "Дрип-лоадаут",
      "description": "Стили + цвета, раскладка как на персонаже.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-drip.html",
      "title": "Дрип по цветам",
      "description": "Экип по цветам (песок, чёрный, MC…) + score статов.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-food.html",
      "title": "Еда и вода",
      "description": "Пища / вода: energy, hydration, цена, рейтинг ₽/очко.",
      "icon": "med",
      "cat": "med",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-gun-budget.html",
      "title": "Сборка за N ₽",
      "description": "Оружие под бюджет: максимум статов, схема модов, прицел.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-gun-builder.html",
      "title": "Сборка оружия",
      "description": "Схема (дуло←приклад), зоны, зум, Auto Build.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-gun-rating.html",
      "title": "Рейтинг оружия",
      "description": "Оружие по цене, патронам, модам, эрго/отдаче и доступности.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-headphones.html",
      "title": "Наушники",
      "description": "Характеристики наушников из API, рейтинг цена/слух, фильтры.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-helmets.html",
      "title": "Шлемы",
      "description": "Класс, зоны, штрафы; наведение — ricochet / blunt / слоты.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-hideout-mgmt.html",
      "title": "Качатель Hideout Management",
      "description": "Какой крафт крутить на каждой станции за минимум ₽ за цикл скилла.",
      "icon": "hideout",
      "cat": "hideout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-hideout.html",
      "title": "Трекер убежища",
      "description": "Уровни станций, шоплист апгрейдов, цены.",
      "icon": "hideout",
      "cat": "hideout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-hitboxes.html",
      "title": "Хитбоксы и урон",
      "description": "Механика HP, хитбоксов, переноса урона + симулятор попаданий",
      "icon": "util",
      "cat": "util",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-item-use.html",
      "title": "Что с предметом",
      "description": "Ввёл предмет — продажа, крафт, убежище, квесты, бартер.",
      "icon": "other",
      "cat": "other",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-keys.html",
      "title": "Ключи",
      "description": "Ключи по локациям, цена и рейтинг.",
      "icon": "other",
      "cat": "other",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-lang-search.html",
      "title": "Локализатор",
      "description": "Поиск предметов и квестов по именам в выбранных языках API.",
      "icon": "other",
      "cat": "other",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-loadout-budget.html",
      "title": "Лоадаут за N ₽",
      "description": "Полный лоадаут под бюджет — заглушка.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-loadout-builder.html",
      "title": "Лоадаут-билдер",
      "description": "Сборка лоадаута с сохранением и загрузкой пресетов.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-loot-slot.html",
      "title": "Лут ₽/слот",
      "description": "Цена за клетку: flea и торговец, пометка квеста.",
      "icon": "other",
      "cat": "other",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-mags.html",
      "title": "Магазины",
      "description": "Магазины по калибрам: ёмкость, эрга, отдача.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-marathon.html",
      "title": "Марафон",
      "description": "Цепочка переходов: расходники, XP, где лутать ресурсы, выходы.",
      "icon": "util",
      "cat": "util",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-medkits.html",
      "title": "Аптечки",
      "description": "HP на клетку, скорость применения, ₽/HP. Аптечки и таблетки.",
      "icon": "med",
      "cat": "med",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-mods.html",
      "title": "Моды",
      "description": "Рейтинг обвесов по статам и совместимости.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-my-tarkov.html",
      "title": "My Tarkov",
      "description": "Дашборд над общим локальным состоянием: убежище, квесты, алерты.",
      "icon": "other",
      "cat": "other",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-nvg.html",
      "title": "ПНВ",
      "description": "Night vision: intensity, noise, diffuse, эвристический score.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-plates.html",
      "title": "Плиты",
      "description": "Эффективность плит: класс, вес, прочность, стоимость ремонта.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-prestige.html",
      "title": "Престижинатор",
      "description": "Окно престижа как инвентарь: клади предметы, собирай набор под деньги / квесты / каппу.",
      "icon": "util",
      "cat": "util",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-price-alarm.html",
      "title": "Сирена цен",
      "description": "Оповещение, когда цена или число офферов пересекает порог",
      "icon": "flea",
      "cat": "flea",
      "kind": "live"
    },
    {
      "file": "tools/tarkovtool-price-track.html",
      "title": "Price track",
      "description": "Flea price history, background snapshots, countdown.",
      "icon": "flea",
      "cat": "flea",
      "kind": "live"
    },
    {
      "file": "tools/tarkovtool-quest-cheese.html",
      "title": "Квест-чиз",
      "description": "Что скрафтить / получить с других квестов для нужного квеста или предмета.",
      "icon": "quests",
      "cat": "quests",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-quest-items.html",
      "title": "Квест-предметы",
      "description": "FIR-предметы для квестов, трекинг.",
      "icon": "quests",
      "cat": "quests",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-quests.html",
      "title": "Квесты · карты",
      "description": "Глоссарий квестов: реальные карты вместо «любая локация», цели по шагам, требования.",
      "icon": "quests",
      "cat": "quests",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-raid-checklist.html",
      "title": "Чек-лист рейда",
      "description": "Сборки под карты, DnD списка, В РЕЙД → сброс галочек через 20 мин.",
      "icon": "quests",
      "cat": "quests",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-random-loadout.html",
      "title": "Рандомный лоадаут",
      "description": "Случайный ган без модов — раскладка как на персонаже.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-repair.html",
      "title": "Починка",
      "description": "Ремонт брони и оружия: качество, стоимость, материалы, скиллы.",
      "icon": "util",
      "cat": "util",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-restock.html",
      "title": "Таймер рестока",
      "description": "Обновление торговцев, пилик, история.",
      "icon": "flea",
      "cat": "flea",
      "kind": "live"
    },
    {
      "file": "tools/tarkovtool-scopes.html",
      "title": "Прицелы",
      "description": "Рейтинг оптики: кратность, ПНВ, community tier.",
      "icon": "loadout",
      "cat": "loadout",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-seasons.html",
      "title": "Сезоны",
      "description": "История сезонов: модификаторы, доки, даты.",
      "icon": "util",
      "cat": "util",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-shopping-list.html",
      "title": "Список покупок",
      "description": "Вишлист после рестока: патроны, мед, флип — с копированием имён.",
      "icon": "flea",
      "cat": "flea",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-shortname.html",
      "title": "Короткие имена",
      "description": "Поиск по short name + цена торговца/flea.",
      "icon": "other",
      "cat": "other",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-skills.html",
      "title": "Скиллы + чизы",
      "description": "Уровень и способ быстрой прокачки каждого навыка.",
      "icon": "other",
      "cat": "other",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-stim-combos.html",
      "title": "Комбо стимуляторов",
      "description": "Связки вроде Meldonin+SJ1, SJ6+Trimadol, Propital+MULE. Иконки и копир.",
      "icon": "med",
      "cat": "med",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-stims.html",
      "title": "Стимуляторы",
      "description": "Рейтинг инъекторов: бой, выносливость, отхил, вес. Эффекты из API.",
      "icon": "med",
      "cat": "med",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-streamer-flip.html",
      "title": "Стример-флип",
      "description": "Ивент-предметы и флип",
      "icon": "flea",
      "cat": "flea",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-trader-flip.html",
      "title": "Трейдер-флип",
      "description": "Покупка у торговца → flea",
      "icon": "flea",
      "cat": "flea",
      "kind": "static"
    },
    {
      "file": "tools/tarkovtool-xp.html",
      "title": "Опыт",
      "description": "Источники XP, множители выхода, калькулятор киллов и таблица уровней.",
      "icon": "util",
      "cat": "util",
      "kind": "static"
    }
  ]
};
(function () {
  var d = window.__TT_CATALOG_DATA;
  if (!d || !d.tools) return;
  window.TarkovHubCATALOG = d.tools;
  window.TarkovHubCatalog = d.tools;
  window.CATALOG = d.tools;
  try {
    window.dispatchEvent(new Event("tarkov-catalog-ready"));
  } catch (e) {}
})();
